// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Shitomo/play-kafka-chat-core/ent/message"
	"github.com/Shitomo/play-kafka-chat-core/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescSenderID is the schema descriptor for sender_id field.
	messageDescSenderID := messageFields[0].Descriptor()
	// message.SenderIDValidator is a validator for the "sender_id" field. It is called by the builders before save.
	message.SenderIDValidator = messageDescSenderID.Validators[0].(func(string) error)
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[1].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
}
